### ISSUE TITLE
Swap usage of module as variable in modules

### ISSUE THREAD

**Issue by jmaguirrei** [themeteorchef/react-pdfs#3]
Hello, after upgrade Meteor to 1.4.2.6 release, server code breaks on startup.

Here is the log.

Having same issue myself at my project, any help will be appreciated!

Thanks

```javascript
W20170213-22:44:16.615(-3)? (STDERR) /home/jmaguirrei/.meteor/packages/meteor-tool/.1.4.2_6.e4csn++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170213-22:44:16.616(-3)? (STDERR) 						throw(ex);
W20170213-22:44:16.617(-3)? (STDERR) 						^
W20170213-22:44:16.618(-3)? (STDERR) 
W20170213-22:44:16.618(-3)? (STDERR) TypeError: Cannot read property 'export' of undefined
W20170213-22:44:16.619(-3)? (STDERR)     at meteorInstall.imports.modules.server.generate-pdf.js (imports/modules/server/generate-pdf.js:1:1)
W20170213-22:44:16.620(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170213-22:44:16.621(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170213-22:44:16.621(-3)? (STDERR)     at Module.Mp.import (/home/jmaguirrei/.meteor/packages/modules/.0.7.9.hfztyw++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170213-22:44:16.622(-3)? (STDERR)     at meteorInstall.imports.api.documents.server.methods.js (imports/api/documents/server/methods.js:1:487)
W20170213-22:44:16.624(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170213-22:44:16.624(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170213-22:44:16.626(-3)? (STDERR)     at Module.Mp.import (/home/jmaguirrei/.meteor/packages/modules/.0.7.9.hfztyw++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170213-22:44:16.627(-3)? (STDERR)     at meteorInstall.imports.startup.server.api.js (imports/startup/server/api.js:1:49)
W20170213-22:44:16.627(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
```

**Comment by themeteorchef** [comment]
Noted. This appears to be a Meteor bug as the error it's throwing is about the `export` keyword which should be compiled as part of Meteor's build tool. If you roll Meteor back a version, does the error still occur?

**Comment by jmaguirrei** [comment]
I went back to 1.4.5 and then to 1.4.3 and still doesn't work.
I didn't see any ticket opened yet also, can you report this?

**Comment by themeteorchef** [comment]
@jmaguirrei Ah, okay. I'd prefer if you submitted as you have reproduction steps on hand.

**Comment by jmaguirrei** [comment]
Ok! Just did it:

https://forums.meteor.com/t/server-code-breaks-after-release-1-4-2-6-cannot-read-property-export-of-undefined/34023

Hope this has a solution. Thanks

**Comment by themeteorchef** [comment]
Thanks, José :)

**Comment by jmaguirrei** [comment]
Hi, problem solved!

Just rename `module` to (for example) `myModule` in **`react-pdfs/imports/modules/server/generate-pdf.js`**

And works again :)

**Comment by themeteorchef** [comment]
Weird! Got it, thank you @jmaguirrei :)

**Comment by jmaguirrei** [comment]
You are welcome! Thanks to you.
